packages:
  - apps/*
  - packages/*

catalog:
  '@auth/core': ^0.37.0
  '@convex-dev/agent': ^0.3.2
  '@convex-dev/auth': ^0.0.90
  alchemy: ^0.82.1
  convex: ^1.31.2
  dotenv: ^17.2.2
  '@types/node': ^25.1.0
  typescript: ^5
  zod: ^4.1.13

ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - workerd

overrides:
  hono@<4.11.7: '>=4.11.7'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
