packages:
  - apps/*
  - packages/*

catalog:
  '@auth/core': ^0.37.0
  '@convex-dev/agent': ^0.3.2
  '@convex-dev/auth': ^0.0.90
  alchemy: ^0.82.1
  convex: ^1.31.2
  dotenv: ^17.2.2
  typescript: ^5
  zod: ^4.1.13

ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - workerd
